# SPDX-FileCopyrightText: Contributors to the Fedora Project
#
# SPDX-License-Identifier: MIT

name: CI
on: [push, pull_request, workflow_dispatch]
jobs:
  python-smoketests-ci:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install absolufy and poetry
        run: |
          python3 -m pip install absolufy-imports poetry

      - name: Enforce relative imports in package
        run: >
          find mirrors_countme -name \*.py -print0
          | xargs -0 absolufy-imports --never

      - name: Check Poetry lock file consistency
        run: >
          poetry lock --check

  backend-ci:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container: fedorapython/fedora-python-tox:latest
    steps:
      - uses: actions/checkout@v3

      - name: Mark the directory as safe for git
        run: git config --global --add safe.directory $PWD

      - name: Install RPM dependencies
        run: |
          dnf -y install coreutils xz gzip

      - name: Install base Python dependencies
        run: |
          python3 -m pip install --upgrade tox

      - name: Install English locale files
        run: |
          dnf install -y glibc-langpack-en

      - name: run tests through tox
        run: tox -e $(tox -l | grep '^py[0-9]' | paste -sd , -)
